### ISSUE TITLE
网络小说下载中文 epub 目录问题

### ISSUE THREAD

**Issue by stonybeach** [FishHawk/auto-novel#11]
网络小说下载成为中日 epub，应该是网站生成的，对吗？

这种由网站生成的中日 epub，目录目前是日语的，我觉得应该设定为中文、或者中日对照比较方便。

在 server/src/main/kotlin/infra/web/makeEpub.kt 里面，为下面好不好？

    val getChapterTitle =
        if (zh) { item: WebNovelTocItem -> item.titleZh ?: item.titleJp }
        else { item: WebNovelTocItem -> item.titleJp }

这样的话，生成的 epub 里面的 toc.ncx 和 OEBPS/Text/nav.xhtml 应该就会变成中文，对吗？

谢谢！并祝新年好。

**Comment by FishHawk** [comment]
ok，过两天我看看。

**Comment by FishHawk** [comment]
修了。一些以前生成的小说可能还没有生效，等更新了就好了。
