### ISSUE TITLE
網站Error code 502登不上去

### ISSUE THREAD

**Issue by terry12369** [FishHawk/auto-novel#129]
如題

請問一下是我網路的問題還是剛好網站上不去

https://imgur.com/FEjZbQK.jpg

沒找到Discord之類的討論區，只好貼在這裡問一下

**Comment by Mlgolhg** [comment]
有遇到一樣的問題 但剛剛翻了一下問題回報好像是開發者在換機器？就只能耐心等候了唄～

**Comment by FishHawk** [comment]
旧机器性能顶不住，又没时间修数据库，所以换了新机器，顺利的话几个小时之后就好了。
