### ISSUE TITLE
Pixiv格式解析升级

### ISSUE THREAD

**Issue by FishHawk** [FishHawk/auto-novel#25]
转QQ群

嵌入图片目前发现有两种格式，一种是[pixivimage:illustid-index]，如https://www.pixiv.net/novel/show.php?id=2753440

还有一种是这样的：https://www.pixiv.net/novel/series/1077755

还有一个[rb: text > desc]（好像是这个格式）代表文字上标的

**Comment by PYUDNG** [comment]
小说插入图片方式一：[uploadedimage:42286]
例：
网页: https://www.pixiv.net/novel/show.php?id=10723739
api: https://www.pixiv.net/ajax/novel/10723739
这种插入的图片直接在api中的`body.textEmbeddedImages[id].urls.original`字段就可以获取到地址

小说插入图片方式二: [pixivimage:38959194]
例：
网页: https://www.pixiv.net/novel/show.php?id=2894162
api: https://www.pixiv.net/ajax/novel/2894162
这种插入的图片需要通过`https://www.pixiv.net/ajax/novel/${novel_id}/insert_illusts?id%5B%5D=${illust_id}&lang=zh`获取

新起一页: [newpage]
例：
网页: https://www.pixiv.net/novel/show.php?id=18549136
api: https://www.pixiv.net/ajax/novel/18549136

文字上标：[[rb:久世彩葉 > くぜ いろは]]
例：
网页: https://www.pixiv.net/novel/show.php?id=10618179
api: https://www.pixiv.net/ajax/novel/10618179

**Comment by FishHawk** [comment]
> 小说插入图片方式一：`[uploadedimage:42286]` 例： 网页: https://www.pixiv.net/novel/show.php?id=10723739 api: https://www.pixiv.net/ajax/novel/10723739 这种插入的图片直接在api中的`body.textEmbeddedImages[id].urls.original`字段就可以获取到地址
> 
> 小说插入图片方式二: `[pixivimage:38959194]` 例： 网页: https://www.pixiv.net/novel/show.php?id=2894162 api: https://www.pixiv.net/ajax/novel/2894162 这种插入的图片需要通过`https://www.pixiv.net/ajax/novel/${novel_id}/insert_illusts?id%5B%5D=${illust_id}&lang=zh`获取
> 
> 新起一页: `[newpage]` 例： 网页: https://www.pixiv.net/novel/show.php?id=18549136 api: https://www.pixiv.net/ajax/novel/18549136
> 
> 文字上标：`[[rb:久世彩葉 > くぜ いろは]]` 例： 网页: https://www.pixiv.net/novel/show.php?id=10618179 api: https://www.pixiv.net/ajax/novel/10618179

终于搞定了，多亏了你的例子，很有帮助。

[newpage] 没啥影响，所以保持原样。

网站现有的小说可以通过“源站同步”来强制刷新，当然翻译也可能会清空。

**Comment by PYUDNG** [comment]
发现了新的marker

小说内章节名`[chapter:【プロローグ】]`，在网页中表现为`<h2><span>【プロローグ】</span></h2>`:
![截屏2024-04-08 下午8 45 09](https://github.com/FishHawk/auto-novel/assets/63054558/decfd765-025c-46fd-96ce-c6e6365bcfac)

例：
网页：https://www.pixiv.net/novel/show.php?id=21893883
api：https://www.pixiv.net/ajax/novel/21893883

**Comment by PYUDNG** [comment]
新的marker和已有旧marker的新解读：

`[newpage]`用于分页，`[jump:N]`用于点击跳转到第N页
例： 
网页：https://www.pixiv.net/novel/show.php?id=22003928
api：https://www.pixiv.net/ajax/novel/22003928

**Comment by PYUDNG** [comment]
新的marker

`[[jumpuri:TEXT > URL]]`相当于markdown中的`[TEXT](URL)`
例：
网页：https://www.pixiv.net/novel/show.php?id=19912145#12
api：https://www.pixiv.net/ajax/novel/19912145
