### ISSUE TITLE
主页上 “我的收藏” 只能显示百度和有道翻译感觉很奇怪

### ISSUE THREAD

**Issue by AkiraChisaka** [FishHawk/auto-novel#47]
![image](https://github.com/FishHawk/auto-novel/assets/47231500/ee2dd2c2-56ef-43be-968e-aa1f73b224fc)

感觉看不到 GPT 和 Sakura 翻译数量很难受。

我之后写个 PR。

**Comment by AkiraChisaka** [comment]
还有这里我想弄成

```
总计 185 / 百度 95 / 有道 150
读到 184 / GPT 12 / Sakura 185
```

这样的感觉

**Comment by AkiraChisaka** [comment]
因为这个功能可能要涉及数据库的 server，所以我还是先等一下再做了。

**Comment by FishHawk** [comment]
done
虽然移动端显示怪怪的

**Comment by AkiraChisaka** [comment]
![image](https://github.com/FishHawk/auto-novel/assets/47231500/23203995-7797-44b0-994a-e916f12c9841)

感觉还行？

![image](https://github.com/FishHawk/auto-novel/assets/47231500/a6c3b524-ad8e-4bf3-bd39-3f7138a6f4da)

跟电脑端看起来差不多的样子
