### ISSUE TITLE
在工作区显示的本地小说列表，是否应该调整使用model或者新建页面的方式阅读小说

### ISSUE THREAD

**Issue by 153264** [FishHawk/auto-novel#57]
在运行翻译器的时候如果想要阅读小说，点击阅读功能页面会直接跳转 
这样会不会影响翻译器的运行？
我是觉得应该调整成新开标签页去阅读小说会好一点，这样既不影响翻译器的运行，也能看翻译完成的小说

**Comment by AkiraChisaka** [comment]
这个是不是搞定了，可以关了？

**Comment by 153264** [comment]
> 这个是不是搞定了，可以关了？

我想着有空改个model层弹出阅读小说

**Comment by FishHawk** [comment]
> > 这个是不是搞定了，可以关了？
> 
> 我想着有空改个model层弹出阅读小说

是想阅读短篇吗？使用逻辑会变得很奇怪。
