### ISSUE TITLE
本地小说的清空文件不知道是不是我的问题，点了清理一直在loading，我看数据库是已经清空了，但是一直在await没有返回

### ISSUE THREAD

**Issue by 153264** [FishHawk/auto-novel#70]
本地小说的清空文件不知道是不是我的问题，点了清理一直在loading，我看数据库是已经清空了，但是一直在await没有返回

_Originally posted by @153264 in https://github.com/FishHawk/auto-novel/issues/68#issuecomment-2143184520_

**Comment by AkiraChisaka** [comment]
啊对的，我好像也有类似的症状呢。

大概就是点了清理以后，强行刷新页面，再点清理，再刷新，好了大概清理完了。

这种感觉。

而 loading 本身是不刷新就永远都在的。

**Comment by 153264** [comment]
那可能要看看这里有什么问题了
[    async deleteAllVolumes() {](https://github.com/FishHawk/auto-novel/blob/3fa0b6f9fce91eb15c125725a2a5e202a454e71e/web/src/pages/bookshelf/BookshelfLocalStore.ts#L163)

**Comment by FishHawk** [comment]
似乎是因为数据库在别的地方被打开了，所以卡住了。改成了朴素的挨个删除。
