### ISSUE TITLE
收藏夹页面里，右侧的边栏无法上下滚动

### ISSUE THREAD

**Issue by AkiraChisaka** [FishHawk/auto-novel#71]
![image](https://github.com/FishHawk/auto-novel/assets/47231500/1818da17-d0f8-40bb-ba22-0855828b95a0)

就是说，收藏夹界面右侧的边栏没法滚下去看到下面的选项。

所以对于我这种收藏夹分类很多的人来说，就没法看到最下面的本地小说了（悲伤

**Comment by 153264** [comment]
我试着处理一下

**Comment by AkiraChisaka** [comment]
> 我试着处理一下

超感谢~

**Comment by 153264** [comment]
emm，我这边创建失败了
![image](https://github.com/FishHawk/auto-novel/assets/36463512/f2a72c48-5a2b-4b3b-9992-3fb1c26298fa)

**Comment by AkiraChisaka** [comment]
> emm，我这边创建失败了

啊，震惊

我把你的 PR 当下来看一下好了

**Comment by 153264** [comment]
> > emm，我这边创建失败了
> 
> 啊，震惊
> 
> 我把你的 PR 当下来看一下好了

我本地mock了一些数据，看起来是正常了
