### ISSUE TITLE
有没有办法可以在翻译或导入小说的时候，无视所有的日文的注音？

### ISSUE THREAD

**Issue by AkiraChisaka** [FishHawk/auto-novel#73]
就是说，有不少日文小说里，作者很喜欢给单词注音，有用没用的词都注上音，导致翻译的时候很奇怪。

比如说：
![image](https://github.com/FishHawk/auto-novel/assets/47231500/58369827-fb38-4cf9-ab9f-0a266d9a7358)
![image](https://github.com/FishHawk/auto-novel/assets/47231500/27bb07f0-e3e0-4799-bd92-319c2860cecc)
![image](https://github.com/FishHawk/auto-novel/assets/47231500/efb2aea5-ec21-4922-a4d7-e67b8f4577bd)

因为作者只是在标记单词要怎么读，所以Sakura只能强行把同一个词翻译两边，或者注上日文假名，又或者注上英文。

感觉这些注音在中文里特别影响阅读。而就算没有这些注音，其实文章的意思也不会有太大的改变。

所以我在想，有没有办法可以在翻译的时候无视这些括号里的注音。或者增加一个选项，在导入小说（或源站同步）的时候不把注音转化成括号？

**Comment by FishHawk** [comment]
已经做了。旧的小说需要用源站同步刷新。

**Comment by AkiraChisaka** [comment]
> 已经做了。旧的小说需要用源站同步刷新。

啊，感谢！

顺便好奇问一下，这个功能是可以选择关闭的，还是说现在统一都无视注音了？

**Comment by AkiraChisaka** [comment]
> 已经做了。旧的小说需要用源站同步刷新。

还有，源站同步是开始翻译每一章的时候抹掉原本的东西，还是开始任务的时候把整本书都抹掉？

因为是个300万字的很多人在读的小说……所以如果一次性全抹掉的话……似乎正在读的人会比较痛苦

**Comment by FishHawk** [comment]
> 还有，源站同步是开始翻译每一章的时候抹掉原本的东西，还是开始任务的时候把整本书都抹掉？

每一章单独检查。

> 顺便好奇问一下，这个功能是可以选择关闭的，还是说现在统一都无视注音了？

**Comment by AkiraChisaka** [comment]
了解了，感谢~
