### ISSUE TITLE
”源站同步“ 这个功能似乎跟 ”过期“ / ”重翻“ 这些功能有冲突的样子，所以 UI 要不要改到一起？

### ISSUE THREAD

**Issue by AkiraChisaka** [FishHawk/auto-novel#76]
就是说，似乎打开 ”源站同步“ 这个选项以后，翻译的 ”常规“ / ”过期“ / ”重翻“ 的选项就一定程度上被无视了？

![image](https://github.com/FishHawk/auto-novel/assets/47231500/676a26bf-cb15-44a8-96d1-087c8387c105)

比如说这里，“源站同步” 以后，应该是 ”常规“ 模式，但是还是自动更新了术语表。

所以感觉大概让 ”源站同步“ 覆盖掉这个选项比较好？就是说，把 “源站同步” 也放到左边的三个选项旁边？

![image](https://github.com/FishHawk/auto-novel/assets/47231500/ea5bce46-1b7f-4172-abfa-ebf6ee356fdc)

**Comment by AkiraChisaka** [comment]
不过接下来的问题是，“源站同步” 是在干什么来着？

似乎是……先检查一下这章跟小说网站上是不是一样的，如果不一样的话就完全重翻这一话。

而如果一样的话……就检查术语表是否过期并只翻译过期的部分？

这么说……似乎也没比较把UI合在一起？只要选上源站同步后，把左边的三个选项作为 ”遇到了没有跟小说网站不符的情况以后该怎么做“ 就可以了？

**Comment by AkiraChisaka** [comment]
> > 这么说……似乎也没比较把UI合在一起？只要选上源站同步后，把左边的三个选项作为 ”遇到了没有跟小说网站不符的情况以后该怎么做“ 就可以了？
> 
> 这和现在是一样的。

嗯呢，那么看来这里有个Bug，最上面的截图里可以看到，这个任务只有 “源站同步” 而没有术语表更新，但是还是检测到术语表变化并开始处理了。

**Comment by FishHawk** [comment]
done
