### ISSUE TITLE
【功能建议】阅读历史希望新增“暂停记录历史”，“清空历史”和“阅读时间”功能

### ISSUE THREAD

**Issue by 153264** [FishHawk/auto-novel#79]
![image](https://github.com/FishHawk/auto-novel/assets/36463512/cfc26ead-324b-4be8-a3a7-dcf9d2bee12d)

**Comment by 153264** [comment]
界面我可以试着调整，但是需要服务器提供接口才行

**Comment by FishHawk** [comment]
ok，不过得等一段时间，优先级不高

**Comment by AkiraChisaka** [comment]
哦！

这么说，“最后阅读时间” 是有在记在账户里的？

**Comment by AkiraChisaka** [comment]
题外话，不过也如果这边的服务器接口调整的话，也求一下 #46 和 #47 的接口。

为了能快速看到有那些小说有没读的更新。

**Comment by FishHawk** [comment]
done
