### ISSUE TITLE
本地小说的下载选项里没有只下载日文的选项

### ISSUE THREAD

**Issue by AkiraChisaka** [FishHawk/auto-novel#83]
![image](https://github.com/FishHawk/auto-novel/assets/47231500/2702a88a-3f90-4d33-b458-3a2f81c2cda7)

感觉似乎还是有个能下载日文原文件的方法比较好。

因为有时候可能不小心把原文件删掉了？

**Comment by FishHawk** [comment]
合理的

**Comment by FishHawk** [comment]
ui比想象的麻烦一点，原始文件下载不能塞进下载设置里面，不是一个东西。

**Comment by AkiraChisaka** [comment]
好耶~ 超感谢！
