### ISSUE TITLE
網站開不了

### ISSUE THREAD

**Issue by cuobai** [FishHawk/auto-novel#91]
![image](https://github.com/FishHawk/auto-novel/assets/74899300/258b2a51-3d0a-4e9a-8441-c652d8674dfd)
網站開不了

**Comment by h0353914** [comment]
我也是
![image](https://github.com/FishHawk/auto-novel/assets/45159732/6cc982dd-278a-49e5-bc50-6cc5893f5607)

**Comment by Genovese0** [comment]
我也是

**Comment by jiejiezi0v0** [comment]
+1

**Comment by kloati** [comment]
今天下午两点四十多开始忽然进不去了

**Comment by FishHawk** [comment]
服务器物理搬迁。因为各种意外叠加导致没法在网站上发公告。

**Comment by FishHawk** [comment]
现在好了，用用看吧

**Comment by pingplug** [comment]
又崩了。。。
