### ISSUE TITLE
我想问下为什么看着看着会发生这种情况

### ISSUE THREAD

**Issue by Cinbider** [FishHawk/auto-novel#95]
![Screenshot_20240723_173749](https://github.com/user-attachments/assets/c19b68e7-eddd-4de9-aa4a-28fb8fd29f40)

**Comment by jiejiezi0v0** [comment]
我也是这样

**Comment by h0353914** [comment]
+1

**Comment by Cocolate486** [comment]
+1

**Comment by Bookytea** [comment]
+1

**Comment by FishHawk** [comment]
服务器挑了个完美的时机关机了，所有人都不在，周六才有人能去开机

**Comment by bennylii** [comment]
XD 难道是手动操作的服务器吗。。。。

**Comment by 35031-mmo** [comment]
+1

**Comment by Nixonball** [comment]
Thank you

**Comment by FishHawk** [comment]
> XD 难道是手动操作的服务器吗。。。。

是家庭小主机，主打一个0成本。本来一个月前就该上云的，但是各种事情环环相扣，完全没办法继续开发。看我的github提交记录就知道了。

**Comment by storicanne** [comment]
半夜時有好了一下下，現在又關機了

**Comment by holzora** [comment]
站长该上云了😂

> > XD 难道是手动操作的服务器吗。。。。
> 
> 是家庭小主机，主打一个0成本。本来一个月前就该上云的，但是各种事情环环相扣，完全没办法继续开发。看我的github提交记录就知道了。
